version: '3'

services:

  api:
    container_name: ml-api
    restart: always
    build: ./api
    networks:
      - networkapi
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes: ['./api:/api', './run_tests.py:/run_tests.py']

  db:
    container_name: ml-db
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=password123"
      - "MYSQL_DATABASE=jazzydb"
      - "MYSQL_USER=rootuser"
    ports:
      - "33061:3306"
    networks:
      - networkapi
    expose:
      - "3306"

volumes:
  dbdata:

networks:
  networkapi: